//PSUEDO CODE-BASICCARD FILE//
//=================================//


//FILE MUST DEFINE A NODE MODULE THAT EXPORTS A CONSTRUCTOR FOR CREATING BASIC FLASHCARDS. EXAMPLE
//MODULE.EXPORTS = BASICCARD
//LOAD INQUIRER NODE PACKAGE
//LOAD NODE FS PACKAGE TO READ/WRITE TO LOG.TXT FILE
//CREATE BASICCARD CONSTRUCTOR FUNCTION THAT WILL ACCEPT TWO ARGUEMENTS: TEXT & CLOZE.
