//PSUEDO CODE-CLOZECARD FILE//
//=================================//

//BUILDOUT CLOZECARD FUNCTIONALITY.
//CREATE A MODULE THAT WILL EXPORT A CONSTRUCTOR FOR CREATING CLOZE-DELETION FLASHCARDS
//EXAMPLE: MODUELE.EXPORTS=CLOZECARD
